In [11]:
#NUMPY QUestions

import numpy as np

A = np.array([1, 5, 7, 9, 12])
B = np.array([5, 9, 11, 15, 7])

print("Array A:", A)
print("Array B:", B)

# Vertical stack
vert_stack = np.vstack((A, B))
print("Vertical Stack:\n", vert_stack)

# Horizontal stack
horiz_stack = np.hstack((A, B))
print("Horizontal Stack:\n", horiz_stack)


Array A: [ 1  5  7  9 12]
Array B: [ 5  9 11 15  7]
Vertical Stack:
 [[ 1  5  7  9 12]
 [ 5  9 11 15  7]]
Horizontal Stack:
 [ 1  5  7  9 12  5  9 11 15  7]


In [12]:
common = []
for a in A:
    for b in B:
        if a == b:
            common.append(a)
print("Common elements:", common)


Common elements: [np.int64(5), np.int64(7), np.int64(9)]


In [13]:
in_range = []
for a in A:
    if a >= 5 and a <= 10:
        in_range.append(a)
print("Numbers in range 5 to 10:", in_range)


Numbers in range 5 to 10: [np.int64(5), np.int64(7), np.int64(9)]


In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_r = []
for row in iris_2d:
    if row[2] > 1.5 and row[0] < 5.0:
        filtered_r.append(row)
print("Filtered iris rows:")
for r in filtered_r:
    print(r)

Filtered iris rows:
[4.8 3.4 1.6 0.2]
[4.8 3.4 1.9 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[4.9 2.4 3.3 1. ]
[4.9 2.5 4.5 1.7]


In [15]:
#PANDAS Question
#1. Filter every 20th row for specific columns

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print("Every 20th row - Manufacturer, Model, Type:")
for i in range(0, len(df), 20):
    print(df.loc[i, ['Manufacturer', 'Model', 'Type']].values)

print()

#2. Replace missing values with mean
min_mean = df['Min.Price'].mean()
max_mean = df['Max.Price'].mean()
for i in range(len(df)):
    if pd.isna(df.loc[i, 'Min.Price']):
        df.loc[i, 'Min.Price'] = min_mean
    if pd.isna(df.loc[i, 'Max.Price']):
        df.loc[i, 'Max.Price'] = max_mean
print("After replacing missing values in Min.Price and Max.Price:")
for i in range(len(df)):
    print(df.loc[i, ['Min.Price','Max.Price']].values)

#3. Rows with row sum > 100
import numpy as np
import pandas as pd
df2 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print("Rows with sum > 100:")
for i in range(len(df2)):
    row_sum = 0
    for j in range(4):
        row_sum = row_sum + df2.iloc[i,j]
    if row_sum > 100:
        print(df2.iloc[i].values)


Every 20th row - Manufacturer, Model, Type:
['Acura' 'Integra' 'Small']
['Chrysler' 'LeBaron' 'Compact']
['Honda' 'Prelude' 'Sporty']
['Mercury' 'Cougar' 'Midsize']
['Subaru' 'Loyale' 'Small']

After replacing missing values in Min.Price and Max.Price:
[np.float64(12.9) np.float64(18.8)]
[np.float64(29.2) np.float64(38.7)]
[np.float64(25.9) np.float64(32.3)]
[np.float64(17.118604651162787) np.float64(44.6)]
[np.float64(17.118604651162787) np.float64(21.45909090909091)]
[np.float64(14.2) np.float64(17.3)]
[np.float64(19.9) np.float64(21.45909090909091)]
[np.float64(22.6) np.float64(24.9)]
[np.float64(26.3) np.float64(26.3)]
[np.float64(33.0) np.float64(36.3)]
[np.float64(37.5) np.float64(42.7)]
[np.float64(8.5) np.float64(18.3)]
[np.float64(11.4) np.float64(11.4)]
[np.float64(13.4) np.float64(16.8)]
[np.float64(13.4) np.float64(18.4)]
[np.float64(14.7) np.float64(18.0)]
[np.float64(14.7) np.float64(18.6)]
[np.float64(18.0) np.float64(19.6)]
[np.float64(34.6) np.float64(41.5)]
[np.float6